name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.brandza99 }}
          password: ${{ secrets.dckr_pat_h4Le6aZmRztQvDiYgusurU_a2_w }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.brandza99 }}/globaldevopschallenge2:latest
            ${{ secrets.dckr_pat_h4Le6aZmRztQvDiYgusurU_a2_w }}/globaldevopschallenge2:v2
